/*
Author : Yeshwanth D S
 Problem Statement
 
 This problem is a programming version of Problem 2 from projecteuler.net
 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1,2,3,5,8,13,21,34,55,89,⋯
 By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
 
 Input Format
 First line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer, N.
 
 Output Format
 Print the required answer for each test case.
 
 Constraints
 1≤T≤105
 10≤N≤4×1016
 Sample Input
 
 2
 10
 100
 Sample Output
 
 10
 44

Problem Source : hackerrank.com (Contest)
Problem Link : https://www.hackerrank.com/contests/projecteuler/challenges/euler002
*/

#include <cmath>
#include <cstdio>
#include <vector>
#include <iostream>
#include <algorithm>
using namespace std;


int main() {
    long T;
    cin>>T;
    while(T--)
    {
        long long  fibo = 1,temp = 0,next = 0,num,sum = 0;
        cin>>num;
        while(fibo < num)
        {
            temp += next;
            next = fibo;
            fibo = temp;
            if(fibo % 2 ==0 && fibo < num)
                sum += fibo;
        }
        cout<<sum<<endl;
    }
    return 0;
}